Thank yuo

### Data Cleaning

In [2]:
import numpy as np
import pandas as pd
import sklearn

In [4]:
df= pd.read_csv('data/profiles_revised.csv')
# df.drop(['essay0','essay1','essay6','essay7','essay8','essay2','essay3','essay4','essay5','essay9'], axis=1)

df

,age,body_type,diet,drinks,drugs,education,ethnicity,height,income,job,offspring,orientation,pets,religion,sex,sign,smokes,speaks,status
0,22,a little extra,strictly anything,socially,never,working on college/university,"asian, white",75.0,-1,transportation,"doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism and very serious about it,m,gemini,sometimes,english,single
1,36,average,mostly other,often,sometimes,working on space camp,white,70.0,80000,hospitality / travel,"doesn&rsquo;t have kids, but might want them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,cancer,no,"english (fluently), spanish (poorly), french (...",single
2,37,thin,anything,socially,NaN,graduated from masters program,NaN,68.0,-1,NaN,NaN,straight,has cats,NaN,m,pisces but it doesn&rsquo;t matter,no,"english, french, c++",available
3,22,thin,vegetarian,socially,NaN,working on college/university,white,71.0,20000,student,doesn&rsquo;t want kids,straight,likes cats,NaN,m,pisces,no,"english, german (poorly)",single
4,30,athletic,NaN,socially,never,graduated from college/university,"asian, black, other",66.0,-1,artistic / musical / writer,NaN,straight,likes dogs and likes cats,NaN,m,aquarius,no,english,single
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59941,60,NaN,NaN,socially,never,graduated from college/university,NaN,62.0,-1,sales / marketing / biz dev,has kids,straight,has dogs,catholicism but not too serious about it,f,cancer and it&rsquo;s fun to think about,no,english,single
59942,24,fit,mostly anything,often,sometimes,working on college/university,"white, other",72.0,-1,entertainment / media,doesn&rsquo;t have kids,straight,likes dogs and likes cats,agnosticism,m,leo but it doesn&rsquo;t matter,no,english (fluently),single
59943,41,average,mostly anything,not at all,never,graduated from masters program,asian,71.0,100000,construction / craftsmanship,doesn&rsquo;t have kids,straight,NaN,christianity but not too serious about it,m,sagittarius but it doesn&rsquo;t matter,no,english (fluently),single
59944,26,athletic,mostly anything,socially,often,working on college/university,"asian, black",73.0,-1,medicine / health,"doesn&rsquo;t have kids, but wants them",straight,likes dogs and likes cats,agnosticism but not too serious about it,m,leo and it&rsquo;s fun to think about,trying to quit,"english (fluently), spanish (poorly), chinese ...",single
59945,40,average,NaN,socially,NaN,graduated from masters program,white,68.0,-1,medicine / health,NaN,gay,likes dogs and likes cats,catholicism and laughing about it,m,gemini and it&rsquo;s fun to think about,sometimes,english,single

In [35]:
#select columns for analysis
df = df[['age','status','sex','orientation','ethnicity','height','income']]
#dropping NA values
df['height'].dropna()
df['income'].dropna()

df

       age     status sex orientation            ethnicity  height  income
0       22     single   m    straight         asian, white    75.0      -1
1       35     single   m    straight                white    70.0   80000
2       38  available   m    straight                  NaN    68.0      -1
3       23     single   m    straight                white    71.0   20000
4       29     single   m    straight  asian, black, other    66.0      -1
...    ...        ...  ..         ...                  ...     ...     ...
59941   59     single   f    straight                  NaN    62.0      -1
59942   24     single   m    straight         white, other    72.0      -1
59943   42     single   m    straight                asian    71.0  100000
59944   27     single   m    straight         asian, black    73.0      -1
59945   39     single   m         gay                white    68.0      -1

[59946 rows x 7 columns]